### ISSUE TITLE
REGRESSION: scan_decisions upsert fails on every poll — #1077 kwargs missing from signature

### ISSUE THREAD

**Issue by P0K5** [P0K5/MeteoEdge#1087]
## Context

**Live regression introduced by PR #1086 (#1077), deployed to the bot host
2026-08-28 11:25 UTC. `scan_decisions` is currently writing nothing.**

Every bracket, every poll, logs:

```
[scan_decisions] upsert failed for 0x5eefef438f5b7b01c9...:
Database.upsert_scan_decision() got an unexpected keyword argument 'yes_bid_raw'
```

Cause: `Database.upsert_scan_decision()` (`src/data/db.py:1294`) gained
`yes_price_raw`/`no_price_raw` in #1076, but PR #1086 added the #1077 order-book
kwargs (`yes_bid_raw`, `no_bid_raw`, `*_bid_levels`, `*_ask_levels`,
`*_book_status`) to the CALL SITE without adding them to the signature. Python
raises `TypeError`, and the caller catches it and logs a WARNING.

`bracket_evals` is unaffected — verified live, rows carry the new fields
correctly. So the primary sink is fine and no rollback is needed. `scan_decisions`
is the secondary sink and is losing every row.

**This is #913 in action.** That issue ("scan_decisions upsert failures are still
silently swallowed — no alerting, no health-report surfacing, no fail-loud") is
still open, and it is the only reason a total write failure survived a deploy
validation. Fix both together.

## Acceptance criteria

- [ ] `upsert_scan_decision()` accepts every kwarg its call site passes, with the
      corresponding columns added to `scan_decisions` via the existing additive
      migration path (`src/data/db.py:379`)
- [ ] Book fields are nullable and default to `None`, matching the `bracket_evals`
      semantics from #1077 (`None` = not attempted, never a fabricated value)
- [ ] A fresh poll on the host writes `scan_decisions` rows with zero warnings
- [ ] **Fail loud (#913):** a `scan_decisions` upsert failure is no longer a bare
      WARNING — it increments a counter surfaced in the daily health report, and a
      sustained failure rate raises an explicit alarm. A 100%-failure poll must be
      impossible to miss.
- [ ] A test asserts the call site and the signature cannot drift again — e.g.
      construct the kwargs the scanner actually passes and assert the method
      accepts them, so adding a field to one side without the other fails CI

## Technical notes

- Call site: `src/scripts/run.py` (the `[scan_decisions] upsert failed` handler).
- Signature: `src/data/db.py:1294`.
- The drift-guard test is the point of this issue, not the column list. This is the
  second sink-divergence class defect in this codebase (see #871); a test that
  pins caller-to-signature agreement is what stops a third.

## Test requirements

- Unit: every kwarg passed by the scanner is accepted; unknown kwarg still raises
- Unit: book fields persist as NULL when not attempted, and round-trip when set
- Regression: a simulated upsert failure surfaces in the health report counter
- Migration: an existing `scan_decisions` table gains the new columns idempotently

## Dependencies

None. **Deploy as soon as merged** — data is being lost every 5 minutes.
Closes the fail-loud half of #913.
